name: ✨ Feature Request
description: Suggest a new feature or improvement for Atometa
title: "[FEATURE] "
labels: ["enhancement", "needs discussion"]
body:
  - type: markdown
    attributes:
      value: |
        Great idea! Please describe your feature request clearly.

  - type: textarea
    id: description
    attributes:
      label: Description
      description: What feature or improvement would you like to see?
      placeholder: "Example: Add support for rendering double/triple bonds differently."
    validations:
      required: true

  - type: textarea
    id: motivation
    attributes:
      label: Motivation / Use Case
      description: Why is this feature useful? Who would benefit? (e.g. researchers, students, drug discovery)
      placeholder: "This would help visualize protein-ligand interactions more clearly in education."
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Did you try other tools or workarounds? What didn't work?

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Any mockups, references to papers, or related tools?

  - type: dropdown
    id: priority
    attributes:
      label: How important is this to you?
      options:
        - Nice to have
        - Useful
        - Important
        - Critical for my work/research
      default: 1